// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sample.proto
package com.github.takahirom.sample.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class MyProtoSample(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  val id: Long? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val name: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val roles: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<MyProtoSample, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MyProtoSample) return false
    return unknownFields == other.unknownFields
        && id == other.id
        && name == other.name
        && roles == other.roles
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + roles.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (id != null) result += """id=$id"""
    if (name != null) result += """name=$name"""
    if (roles.isNotEmpty()) result += """roles=$roles"""
    return result.joinToString(prefix = "MyProtoSample{", separator = ", ", postfix = "}")
  }

  fun copy(
    id: Long? = this.id,
    name: String? = this.name,
    roles: List<String> = this.roles,
    unknownFields: ByteString = this.unknownFields
  ): MyProtoSample = MyProtoSample(id, name, roles, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<MyProtoSample> = object : ProtoAdapter<MyProtoSample>(
      FieldEncoding.LENGTH_DELIMITED, 
      MyProtoSample::class
    ) {
      override fun encodedSize(value: MyProtoSample): Int = 
        ProtoAdapter.INT64.encodedSizeWithTag(1, value.id) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.name) +
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.roles) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: MyProtoSample) {
        ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.roles)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): MyProtoSample {
        var id: Long? = null
        var name: String? = null
        val roles = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.INT64.decode(reader)
            2 -> name = ProtoAdapter.STRING.decode(reader)
            3 -> roles.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return MyProtoSample(
          id = id,
          name = name,
          roles = roles,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: MyProtoSample): MyProtoSample = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
